- src/ws-dropdown/ws-dropdown.js
Add icon property to show an icon inside the dropdown toggle.
```html
<ws-dropdown text="Click me" icon="icon-ok icon16" item="...." />
```
> Added icon to dropdown toggle

- src/ws-week-picker/ws-week-picker.scss
there was one styling issue missing.
big sry
> Ws week picker preact

- src/ws-date-picker/ws-date-picker.scss
- src/ws-header/ws-header.scss
- src/ws-inline-edit/ws-inline-edit.scss
- src/ws-notification/ws-notification.scss
Adding new variables for spacings according to the Design System Updates, see screenshot below:
> Adding new variables for spacings according to the Design Sys

- demo/index.scss
- dist/amd/ws-header/ws-header.scss
- dist/amd/ws-notification/ws-notification.scss
- dist/amd/ws-week-picker/ws-week-picker-calendar.js
- dist/amd/ws-week-picker/ws-week-picker.js
- dist/amd/ws-week-picker/ws-week-picker.scss
- dist/commonjs/ws-header/ws-header.scss
- dist/commonjs/ws-notification/ws-notification.scss
- dist/commonjs/ws-week-picker/ws-week-picker-calendar.js
- dist/commonjs/ws-week-picker/ws-week-picker.js
- dist/commonjs/ws-week-picker/ws-week-picker.scss
- dist/es2015/ws-header/ws-header.scss
- dist/es2015/ws-notification/ws-notification.scss
- dist/es2015/ws-week-picker/ws-week-picker-calendar.js
- dist/es2015/ws-week-picker/ws-week-picker.js
- dist/es2015/ws-week-picker/ws-week-picker.scss
- dist/system/ws-header/ws-header.scss
- dist/system/ws-notification/ws-notification.scss
- dist/system/ws-week-picker/ws-week-picker-calendar.js
- dist/system/ws-week-picker/ws-week-picker.js
- dist/system/ws-week-picker/ws-week-picker.scss
- src/ws-header/ws-header.scss
- src/ws-notification/ws-notification.scss
- src/ws-week-picker/ws-week-picker.scss
Fixed components regarding to atomic design branch
> Adopted atomic design changes

- demo/demo_app.js
- demo/index.scss
- demo/mockdata.js
- dist/amd/index.js
- dist/amd/ws-tiles-chart/tile.js
- dist/amd/ws-tiles-chart/ws-tiles-chart.js
- dist/amd/ws-tiles-chart/ws-tiles-chart.scss
- dist/commonjs/index.js
- dist/commonjs/ws-tiles-chart/tile.js
- dist/commonjs/ws-tiles-chart/ws-tiles-chart.js
- dist/commonjs/ws-tiles-chart/ws-tiles-chart.scss
- dist/es2015/index.js
- dist/es2015/ws-tiles-chart/tile.js
- dist/es2015/ws-tiles-chart/ws-tiles-chart.js
- dist/es2015/ws-tiles-chart/ws-tiles-chart.scss
- dist/system/index.js
- dist/system/ws-tiles-chart/tile.js
- dist/system/ws-tiles-chart/ws-tiles-chart.js
- dist/system/ws-tiles-chart/ws-tiles-chart.scss
- src/index.js
- src/ws-tiles-chart/tile.js
- src/ws-tiles-chart/ws-tiles-chart.js
- src/ws-tiles-chart/ws-tiles-chart.scss
Created - Tiles chart Component
- The component scales the tiles based on the number of tiles and the chart width and height props
- Tile colors, maximum size, minimum size and data is configurable
- The component was added to the demo page as an example of use
See how it looks like.
> Tiles chart component

- tests/test-component.js
- tests/ws-header/ws-header.spec.js
I did a pretty simple but usefull enhancement by simplifying the creation of test components.
> Created test component class to simplify tests

- dist/amd/ws-dropdown/ws-dropdown.js
- dist/amd/ws-header/ws-header-nav-link.js
- dist/amd/ws-header/ws-header.js
- dist/commonjs/ws-dropdown/ws-dropdown.js
- dist/commonjs/ws-header/ws-header-nav-link.js
- dist/commonjs/ws-header/ws-header.js
- dist/es2015/ws-dropdown/ws-dropdown.js
- dist/es2015/ws-header/ws-header-nav-link.js
- dist/es2015/ws-header/ws-header.js
- dist/system/ws-dropdown/ws-dropdown.js
- dist/system/ws-header/ws-header-nav-link.js
- dist/system/ws-header/ws-header.js
- src/ws-header/ws-header.js
Fixing a bug in Authentication URL that it had newlines which Omer reported
> fix(header): Fixing a bug in Authentication URL that it had newlines

- MAINTAINERS
Sorry for that typo. Just copy&pasting emails from gmail.
> wrong mail of inanda

- PULL_REQUEST_TEMPLATE.md
A simple pull Request template for our components.
Most of the time we are missing some references to existing issues, are not updating them etc. With a PR template we create some more visibility
> Create PR template

- package.json
Pull request for issue: #
Are there more related issue(s): # #
Description (short):
> fix(package): Change version

- package.json
Pull request for issue: #77 
This PR introduces a automatic tag and GitHub release version to be created when the master or release branch is build. So if you push to any other branch just the styleguide gets built but if a PR will be merged to the master the build also bumps the package version, generates a changelog, updates the dist folder, creates a new git tag and creates a new release on GitHub.
> fix(package): adjusted the package version

- src/ws-dropdown/ws-dropdown.js
Pull request for issue: #75
Are there more related issue(s): # #
Description (short):
> Drop down support for disabled property

- CONTRIBUTING.MD
No real issue given
A short update on contributing.md regarding how our commit messages should look like.
> docs(contributing.md): Updated Contrib guidelines

- CONTRIBUTING.MD
- src/ws-week-picker/ws-week-picker-calendar.js
- src/ws-week-picker/ws-week-picker.js
- src/ws-week-picker/ws-week-picker.scss
Pull request for issue: #30
Component was broken because of some typos. + Added new styling by UX.
> Ws week picker

- src/ws-dropdown/ws-dropdown.js
Pull request for issue: #93
- Show correct label for preselected value
> fix(dropdown): Show correct label for preselected value

- demo/demo_app.js
- package.json
- src/ws-dropdown/ws-dropdown.js
- src/ws-notification/ws-notification.scss
If you select the dropdown type select the dropdown container will have the same width as the select element
> fix(dropdown): Made dropdown as wide as select is

- src/ws-date-picker/ws-date-picker.scss
- src/ws-week-picker/ws-week-picker-calendar.js
- src/ws-week-picker/ws-week-picker.scss
Fixed QA review issues on date and week picker.
> Fixed date week picker

- src/ws-dropdown/ws-dropdown.js
- src/ws-header/ws-header.js
- src/ws-header/ws-header.scss
- Fixed displayed text for dropdowns which are not from type select
- Fixed styling of application logo in ws-header
> Fixed dropdown text and header logo

- demo/index.scss
- doc/components/spinner.md
- src/index.js
- src/index.scss
- src/ws-spinner/ws-spinner.js
- src/ws-spinner/ws-spinner.scss
- src/ws-week-picker/ws-week-picker.scss
- tests/index.scss
Issue: #114 
Screenshot:
Description: 
I added the spinner in a slightly different way than materializecss has it. 
Example:
```html
<ws-spinner size="small" is-white></ws-spinner>
```
> feat(spinner): Created spinner component

- doc/components/notification.md
Pull request for issue: #
Are there more related issue(s): # #
Description (short):
> documentation update

- doc/components/dropdown.md
Pull request for issue: #121 
This PR will:
* Remove unnecessary conflict markers that got there by mistake.
> Remove merge conflict markers from dropdown docs

- demo/demo_app.js
- demo/index.scss
- doc/components/dropdown.md
- src/ws-dropdown/ws-dropdown.js
- src/ws-tiles-chart/tile.js
- src/ws-tiles-chart/ws-tiles-chart.js
- tests/index.scss
Pull request for issue: #109 
I added a width attribute for dropdowns to be able to specify a custom width per dropdown
> Dropdown improvements

- src/ws-header/ws-header.js
I made the application name as an anchor to "#" so that it should point to the start page of an spa.
> fix(header): Added hash link to home page

- README.MD
Pull request for issue: #117 
This PR:
* fixes references in the README after project renaming.
* includes minor edits in README
> Rename old project references and add minor edits

- src/ws-header/authorization.js
- src/ws-header/ws-header.js
- tests/ws-header/ws-header.spec.js
I removed the refresh token logic since it is not anymore supported by IAM.
> fix(header): Removed refresh token logic

- README.MD
Pull request for issue: #139 
Just a small addition to the README so people see immediately version number and can click (go to) Changelog.md
> docs(changelog): Add a reference with version number to Changelog

- src/ws-header/ws-header.js
- tests/ws-header/ws-header.spec.js
- Login from header was broken and is fixed now
- Fixed initial login state displayed in header
> fix(header): Fixed initial login state and login/logout action from header

- package.json
This saves time and bandwidth during each install, which will make builds go faster.
```text
added 1496 packages
```
```text
added 1492 packages
```
1. Check out this branch
1. `rm -rf node_modules`
1. `npm install`
1. `npm test`
> Remove unused Sinon.JS

- src/ws-header/ws-header.js
For applications which uses the authorization before the header is attached to the DOM it is hard to read the ws-auth-changed event.
Therefore I ensure the authorization is initialized statically with the header class so that it is possible to listen for changes via
```js
WSHeader.authorization.onAccessTokenChange(token => /* do something */)
```
> fix(ws-header): Ensure Authorization was initialized to fetch access token changes without DOMEvent

- src/ws-header/authorization.js
- src/ws-header/json-web-token.js
- Fixed naming of file access-token.js to json-web-token.js
- Fixed serialization of token by adding a toJSON method to the JsonWebToken
> fix(header): Fixed file name and added JSON serializer function to token class

- demo/demo_app.js
- demo/index.html
- demo/index.scss
- src/index.js
- src/index.scss
- src/ws-option-buttons/ws-option-button.scss
- src/ws-option-buttons/ws-option-buttons.js
- tests/ws-option-buttons/ws-option-buttons.spec.js
I created a new component which I called option buttons. This component is right now used only in new PO frontend but possibly will replace all dropdowns / selects with just a few values.
> feat(option-buttons): Created new component called option buttons

- src/index.scss
> fix(option-buttons): Fixed import naming

- doc/components/01-header.md
- doc/components/02-notifications.md
- doc/components/03-dropdowns.md
- doc/components/04-date-pickers.md
This just fixes some typos and grammar problems in the documentation.
> docs(several): some typo/grammar fixes

- circle.yml
- package.json
- webpack.config.preact.test.js
- webpack.config.react.test.js
for #168 
updates the node version from 7.8 to 8.11
changes the spread operator into the slightly dirtier Object.assign syntax
> build(node) update node

- src/ws-dropdown/dropdown-menu-item.js
for #163 
we no longer access the state directly; now using setState
> fix(dropdown) no longer directly accesses the state

- src/ws-date-picker/ws-date-picker.scss
- src/ws-week-picker/ws-week-picker.scss
quick scss fix to add a hover state
normal
hovered
> MISC: ally hover color given to date and week picker

- src/imports.js
- src/ws-date-picker/ws-date-picker.js
- src/ws-dropdown/dropdown-menu-item.js
- src/ws-dropdown/dropdown-menu.js
- src/ws-dropdown/ws-dropdown.js
- src/ws-header/authorization.js
- src/ws-header/json-web-token.js
- src/ws-header/storage/abstract-storage.js
- src/ws-header/storage/cookie-storage.js
- src/ws-header/storage/local-storage.js
- src/ws-header/ws-header.js
- src/ws-inline-edit/ws-inline-edit.js
- src/ws-notification/ws-notification.js
- src/ws-option-buttons/ws-option-buttons.js
- src/ws-spinner/ws-spinner.js
- src/ws-tab-menu/ws-tab-menu.js
- src/ws-tiles-chart/tile.js
- src/ws-tiles-chart/ws-tiles-chart.js
- src/ws-week-picker/ws-week-picker-calendar.js
- src/ws-week-picker/ws-week-picker.js
- tests/test-component.js
- tests/ws-weekpicker/ws-weekpicker.spec.js
I can't move forward with having a huge PR which is also failing and fixes a lot of things + introduces a new component.
-> This will definitely create more bugs and headache for all of us. 
So I take the opportunity again to only fix ESLint Errors, so that CI is at least back to normal. No Doclint warnings, as they are now warnings.
Things I did here:
- I tried to use onKeyPress Only and for almost all cases it shouldn't make a big difference for now, as many onClick Handlers are not relying on the Event Object.
- I had to disable two lines because in one case rewrite is too much effort and second is just ESLint complaining about undef-state which is not true (but it can't understand the state init function).
- I only fixed Errors not Warnings, so the PR is smaller …
> fix(lint): fixing master branch

- demo/demo_app.js
- src/ws-header/ws-header.js
Pull request for issue: #185 
no new component was added
Description (short): Creates the option to chose a target for the Links you create in the header. If no target is set, the link opens in the same window (as before).
> added target prop for wsheader and demo-app
