src/ws-dropdown/ws-dropdown.js

When the value outside changed the new value gets selected but previous values were not unset / deselected.
This is fixed now

bug(dropdown) Fixed value changes from outside 

---

demo/demo_app.js
demo/index.scss
demo/mockdata.js
dist/amd/ws-tiles-chart/tile.js
dist/amd/ws-tiles-chart/ws-tiles-chart.js
dist/amd/ws-tiles-chart/ws-tiles-chart.scss
dist/commonjs/ws-tiles-chart/tile.js
dist/commonjs/ws-tiles-chart/ws-tiles-chart.js
dist/commonjs/ws-tiles-chart/ws-tiles-chart.scss
dist/es2015/ws-tiles-chart/tile.js
dist/es2015/ws-tiles-chart/ws-tiles-chart.js
dist/es2015/ws-tiles-chart/ws-tiles-chart.scss
dist/system/ws-tiles-chart/tile.js
dist/system/ws-tiles-chart/ws-tiles-chart.js
dist/system/ws-tiles-chart/ws-tiles-chart.scss
src/ws-tiles-chart/tile.js
src/ws-tiles-chart/ws-tiles-chart.js
src/ws-tiles-chart/ws-tiles-chart.scss

Tile Chart: Simplify properties and allow tile CSS styling per group
- Simplify the data property passed to the component
- Add the group name as a class to the tile in order to allow styling using CSS
- Add a default tile color to the CSS
- Change Demo page to show how to style the tiles per group using CSS instead of property

Tile chart: Simplify the properties and allow tile styling using css

---

src/ws-dropdown/dropdown-menu.js

Pull request for issue: #88 
It should fix the bug described in the issue when you select but not store elements in a multiple ws-dropdown, do a search and they sometimes disappear.

fix(ws-dropdown): Should fix a small bug regarding the filter function

---

src/ws-tiles-chart/ws-tiles-chart.js

Pull request for issue: #101
- Calculate the tile size also on componentWillReceiveProps, so that it updates when the properties of the component changes and it renders again.

fix(tiles-chart): update tile size when the component updates

---

src/ws-notification/ws-notification.js

Sometimes this error pops up in applications using ws-notification, due to having only one parameter so I added the 2nd one to fix it.

fix(notification): removeEventListener should have 2 arguments not one

---

src/ws-header/storage/local-storage.js

The local storage was using a wrong key and therefore the login could be not working.

fix(header): Fixed wrong key name for local storage

---

demo/demo_app.js
src/ws-date-picker/ws-date-picker.scss
src/ws-dropdown/dropdown-input.js
src/ws-dropdown/dropdown-menu-item.js
src/ws-dropdown/dropdown-menu.js
src/ws-dropdown/ws-dropdown.js
src/ws-header/ws-header.js
tests/ws-dropdown/dropdown-menu.spec.js
tests/ws-dropdown/ws-dropdown.spec.js

To improve the usability I made the dropdown controllable with keyboard.
Use arrow down / up to focus the next or previous item.
Use enter to select / store the focused item.
For multi select's you still have to hit the OK button which can be done with tab + enter.
Note: There are still some small issues in when marking an item as selected and pressing down key again the focus jumps down to the previous selection. This is not critical but I have no more time to fix this.
As well I added unit tests for the most important functions.
@tonysaad Here you can see how I workaround the React event handling :)

Dropdown keyboard control

---

circle.yml

This PR updates git URL in Circle CI configuration, so the CI builds no longer fail.

Update project URL in Circle CI configuration

---

demo/demo_app.js
demo/index.html
demo/mockdata.js
dist/amd/imports.js
dist/commonjs/imports.js
dist/es2015/imports.js
dist/system/imports.js
package-lock.json
package.json
src/imports.js
webpack.config.preact.js

Pull request for issue: #119 
This PR will:
* Upgrade Preact and `preact-compat` to latest stable versions. That will make the demo page run again (#119).
* Fix linting problems in scripts used by the demo page.
* Change the title of the demo page, so it doesn't reference Preact anymore. The demo works just as well with React.
* Remove `peerDependencies` section from `package.json`. All deps listed there are already included in the `dependencies` section.
* Remove fallback for `PureComponent`, since it's now [supported](https://github.com/developit/preact-compat/issues/139) by `preact-compat`.

Make the Demo Work Great Again in Preact Mode

---

package-lock.json
package.json

Pull request for issue: #125 
Our pre-commit hook was causing problems:
1. It was referencing a script that couldn't run unless its permissions were manually fixed.
2. It slowed down the workflow, by running long tests before every commit.
3. It duplicated functionality of the CI server.
In this PR I removed the node module responsible for the pre-commit hook.
After the PR is merged, everyone who checked out the project previously **needs to manually remove the hook files** created by this module. The files are:
`.git/hooks/precommit` 
`.git/hooks/precommit.old`

Remove git pre-commit hook package

---

src/ws-header/ws-header.js
tests/ws-header/ws-header.spec.js

I forgot that the access token consist of 3 parts which I added right now

fix(header): Fixed parsing name from token

---

src/ws-header/ws-header.js

In case someone wants to use the header without displaying login and locale settings there are 2 properties to hide it now. For hiding locale on the header use showLocale={false} and to hide login use showAuthorization={false}. By default these are show.
Also a new property was created to set the rootUrl. By default the value is '#'.

ws-header show optional locale and oauth

---

src/ws-header/ws-header.js

Fixed a referencing error because `this.storage` was compiled to `undefined.storage` for static member

fix(header): With amd build the header thre an error

---

src/ws-header/access-token.js
src/ws-header/authorization.js
src/ws-header/ws-header.js
tests/ws-header/ws-header.spec.js

Instead of return the access token as string and exposing many token related functions from the header I wrapped the token with a class.
This class allows to get the abbreviation of the user the token was issued for and to check if the token is valid based on the expiration date and JSON structure.
```js
WSHeader.storage.set('access_token', 'some.jwt.token');
const token = WSHeader.getAccessToken()
token.isValid() // Returns true if token is not expired
token.getUserAbbreviation() // Returns abbreviation of user the token was issued for e.g. tschlage
token == 'some.jwt.token' // will be true because valueOf returns the token
token === 'some.jwt.token' // will be false because the type is still JsonWebToken
`The token is: ${token}` // The JsonWebToken class implements a toString method
```

feat(header): Added a wrapper for the access token to check expiration of token

---

src/ws-tab-menu/ws-tab-menu.js

Pull request for issue: #151 
OnChange listener of the wstabmenu does not work after component re-render. 
Added ComponentDidUpdate to configure items again.

fix wstabmenu render

---

demo/demo_app.js
doc/components/01-header.md
package.json
src/ws-header/ws-header.js

for #167 
Pull request for issue: LBJ-716
links arent always simple anchors.  in my example i needed a `<Link />` element (react router link) instead of an `<a />`.  this will detect something that isn't a standard object and render it as a component instead

feat(header) Accept custom link elements

---

.eslintrc.js
src/ws-dropdown/ws-dropdown.js
src/ws-header/ws-header.js

Pull request for issue: #171 
custom classnames assignment now available
*****
this ALSO should fix the deployment, by changing the eslint rule `href-no-hash` to `anchor-is-valid`

feat(dropdown): accept custom class

---

src/ws-date-picker/ws-date-picker.scss

now you can click through to the input
Pull request for issue: #179 

fix(datepicker) disabled pointer events on the icon

---

src/ws-date-picker/ws-date-picker.js

the date picker now accepts the className attribute for passing in extra classes - in my use case, an error class
normal:
error:
markup:

fix(datepicker) class is passed in

---

demo/demo_app.js
src/ws-dropdown/ws-dropdown.js

Team Azubis reported an issue with dropdowns when they have type=select and text=anything. The default text is not displayed.
I fixed this issue.

fix(dropdown): Fixed initial text for select dropdowns

---

src/ws-dropdown/dropdown-menu.js
src/ws-multi-select/ws-multi-select.js

The filter inputs of dropdown and multi select were not changeable anymore due to diffences of defaultValue and value in React.

Fixed not changeable filter inputs

---

src/ws-dropdown/dropdown-menu.js
src/ws-overlay/ws-overlay.js

**Explanation of the error:**
A component opens the dropdown when a input got focus and closes the dropdown when blurred. The close works by adding a css class to animate the element and a listener removes mod-open class when the animation is done. When you focus the input and the dd is opened and then switch the tab, chrome and ff will trigger a blur event, the animation is started but actually chrome and ff are not rendering anything. When you then focus the original tab again, the input will be focused and the dropdown is opened and finally chrome renders the close animation^^ At this point the dropdown thinks it's open but it isn't and it's broken. 
**Solution**
before starting the animation add another listener for window blurring to immediately call the callback like the animation …

fix(overlay): Fixed broken components when blurring the tab

---

src/ws-multi-select/ws-multi-select.js
src/ws-overlay/ws-overlay.js

The problem was that close removes the container height and the class mod-open once the animation is finished.
When open() is called within these 200ms the target height is set on the container and the class mod-open is added, then the animatiion finishes and the height and mod-open is removed again.
Afterwards close() can be called again but since there is no change (class already removed and height is 0) the animation end events are never fired and the listener is not removed. So this effect
will be repeated on the next open() and close() call.
To work around this I call the animation end callbacks of started animations before opening the overlay.

fix(overlay): Fixed corrupted state when call open() and close() to fast and often

---

src/ws-inline-edit/ws-inline-edit.js

**Problem**
When the value property changed from outside the value of the input is updated but the width isn't recalculated.
**Solution**
Resize the input after the state change.

fix(inline-edit): Resize inline edit when value changes from outside
